#!/bin/sh
#-
# Copyright (c) 2019 Emmanuel Vadot <manu@FreeBSD.Org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#

############################################################ INCLUDES

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1
f_include $BSDCFG_SHARE/pkgbase.subr || exit 1

############################################################

# Install pkg into the new root
pkg_list="pkg p74-hbsdfw-core python38 beep"
f_pkginstall "HardenedBSD Fireall Core" "$pkg_list"

mkdir -p ${BSDINSTALL_CHROOT}/hbsdfw-installer-pkgs

# XXX (2022-06-15 swebb): Completely ugly hack to force installation of
# otherwise missing packages. On the plus side, this allows us to cache the
# packages that were included in the original install image.
cp -R /usr/freebsd-dist/hbsdfw/ ${BSDINSTALL_CHROOT}/hbsdfw-installer-pkgs/
chroot ${BSDINSTALL_CHROOT} find /hbsdfw-installer-pkgs/All -name \*.pkg | xargs chroot ${BSDINSTALL_CHROOT} pkg add -fM

# TODO add this to the mtree files
mkdir -p ${BSDINSTALL_CHROOT}/conf
mkdir -p ${BSDINSTALL_CHROOT}/var/etc
mkdir -p ${BSDINSTALL_CHROOT}/usr/local/etc/

# TODO ?? don't know yet
cp /conf/config.xml ${BSDINSTALL_CHROOT}/usr/local/etc/config.xml
cp ${BSDINSTALL_CHROOT}/usr/local/etc/pkg/repos/FreeBSD.conf.sample ${BSDINSTALL_CHROOT}/usr/local/etc/pkg/repos/FreeBSD.conf

# Select the console
echo 'boot_multicons="YES"' >> ${BSDINSTALL_CHROOT}/boot/loader.conf.local
echo 'boot_serial="YES"' >> ${BSDINSTALL_CHROOT}/boot/loader.conf.local
echo 'comconsole_speed=115200' >> ${BSDINSTALL_CHROOT}/boot/loader.conf.local
echo 'console=comconsole' >> ${BSDINSTALL_CHROOT}/boot/loader.conf.local


#read -p "Press <CR> to continue... " NOVALUE
